server:
  port: 8085


spring:
  application:
    name: SERVICE-OEDER
  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
