server:
  port: 8084

spring:
  application:
    name: AUTH-SERVICE
  redis:
    host: localhost
    port: 6379
    database: 0




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/





