server:
  port: 8083

spring:
  application:
    name: INVENTORY-SERVICE
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

